household<- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
household$Date <- factor(household$Date)
household$Date<- as.Date(household$Date, format = "%d/%m/%Y")
library(chron)
household$Time<-times(household$Time)
household1 <- subset(household, Date>="2007-02-01" &  Date <= "2007-02-02")
household1$Global_active_power<-as.numeric(levels(household1$Global_active_powe)[household1$Global_active_powe])
png("plot2.png", width = 480, height = 480)
household1 <- transform(household1, datetime=as.POSIXct(paste(household1$Date, household1$Time)), "%d/%m/%Y %H:%M:%S")
plot(household1$datetime,household1$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()