household<- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
household$Date <- factor(household$Date)
household$Date<- as.Date(household$Date, format = "%d/%m/%Y")
library(chron)
household$Time<-times(household$Time)
household1 <- subset(household, Date>="2007-02-01" &  Date <= "2007-02-02")
household1$Global_active_power<-as.numeric(levels(household1$Global_active_powe)[household1$Global_active_powe])
png("plot3.png", width = 480, height = 480)
household1 <- transform(household1, datetime=as.POSIXct(paste(household1$Date, household1$Time)), "%d/%m/%Y %H:%M:%S")
household1$Sub_metering_1 <- as.numeric(as.character(household1$Sub_metering_1))
household1$Sub_metering_2 <- as.numeric(as.character(household1$Sub_metering_2))
household1$Sub_metering_3 <- as.numeric(as.character(household1$Sub_metering_3))
plot(household1$datetime,household1$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(household1$datetime,household1$Sub_metering_2, col="red")    
lines(household1$datetime,household1$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.off()