household<- read.table("household_power_consumption.txt",header = TRUE, sep = ";")
household$Date <- factor(household$Date)
household$Date<- as.Date(household$Date, format = "%d/%m/%Y")
library(chron)
household$Time<-times(household$Time)
household1 <- subset(household, Date>="2007-02-01" &  Date <= "2007-02-02")
household1$Global_active_power<-as.numeric(levels(household1$Global_active_powe)[household1$Global_active_powe])
png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(household1$datetime,household1$Global_active_power, type="l", xlab="", ylab="Global Active Power")
household1$Global_reactive_power <- as.numeric(as.character(household1$Global_reactive_power))
household1$Voltage <- as.numeric(as.character(household1$Voltage))
plot(household1$datetime,household1$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(household1$datetime,household1$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(household1$datetime,household1$Sub_metering_2,col="red")
lines(household1$datetime,household1$Sub_metering_3,col="blue")
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), bty="n", cex=.5)
plot(household1$datetime,household1$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
